fix: fix test function
SeisoLLC/ReleaseHound pull request #4
Opened 2023-08-03 14:20 UTC by ChiefHolland

# Contributor Comments

This PR adds a dependency required by the test task.

## Pull Request Checklist

Thank you for submitting a contribution to ReleaseHound!

In order to streamline the review of your contribution we ask that you review
and comply with the below requirements:

- [x] Rebase your branch against the latest commit of the target branch.
- [x] If you are adding a dependency, please explain how it was chosen.
- [x] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results.
- [x] If there is an issue associated with your Pull Request, link the issue to the PR.
- [x] Validate that documentation is accurate and aligned to any project updates or additions.

2023-08-03 19:08 UTC, JonZeolla requested changes
I don't understand why we need this now but didn't before.  If it is an indirect dep it should get fixed by just freezing the lock file?

2023-08-03 19:16 UTC, ChiefHolland commented
I was confused, too. It passed during the PR but failed the merge.

2023-08-03 20:13 UTC, ChiefHolland commented on tasks.py
> +            stdout=subprocess.PIPE,
Shifted subprocess method IAW https://github.com/orgs/community/discussions/26197

2023-08-03 21:41 UTC, JonZeolla commented on tasks.py
> +            stdout=subprocess.PIPE,
WHAT 😮

2023-08-04 19:54 UTC, JonZeolla commented
This is obsoleted by https://github.com/SeisoLLC/ReleaseHound/pull/5

2023-08-04 19:54 UTC, closed without merging